name: 'marketing_platform'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'marketing_platform'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  marketing_platform:
    # Bronze layer - raw data
    bronze:
      +materialized: view
      +schema: bronze
    
    # Silver layer - cleaned and normalized
    silver:
      +materialized: table
      +schema: silver
    
    # Gold layer - business ready
    gold:
      +materialized: table
      +schema: gold

# Snapshot configurations
snapshots:
  marketing_platform:
    +target_schema: snapshots
    +unique_key: id
    +strategy: timestamp
    +updated_at: updated_at